Update install-node-red-sh

diff --git a/node-red/install-node-red-sh b/node-red/install-node-red-sh
--- a/node-red/install-node-red-sh
+++ b/node-red/install-node-red-sh
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # Version
-VERSION="1.0.4"
+VERSION="1.0.5"
 
 set -e  # Exit immediately if a command exits with a non-zero status.
 
@@ -11,8 +11,8 @@ GREEN='\033[0;32m'
 RED='\033[0;31m'
 NC='\033[0m' # No Color
 
-echo "PiHA-Deployer Node-RED Install Script v$VERSION"
-echo "Script started"
+echo -e "${BLUE}PiHA-Deployer Node-RED Install Script v$VERSION${NC}"
+echo -e "${BLUE}Script started${NC}"
 
 # GitHub repository details
 REPO_OWNER="cdelalama"
@@ -23,13 +23,13 @@ BRANCH="main"
 download_from_github() {
     local file=$1
     local url="https://raw.githubusercontent.com/$REPO_OWNER/$REPO_NAME/$BRANCH/node-red/$file"
-    echo "Downloading $file from $url"
+    echo -e "${BLUE}Downloading $file from $url${NC}"
     curl -s -O "$url"
     if [ $? -ne 0 ]; then
-        echo "Failed to download $file"
-        return 1
+        echo -e "${RED}Failed to download $file${NC}"
+        exit 1
     fi
-    echo "$file downloaded successfully"
+    echo -e "${GREEN}$file downloaded successfully${NC}"
 }
 
 # Default values
@@ -100,7 +100,7 @@ echo "BASE_DIR created successfully"
 
 # Copy .env to BASE_DIR
 echo -e "${BLUE}Copying .env to $BASE_DIR${NC}"
-cp .env "$BASE_DIR/"
+cp .env "$BASE_DIR/.env"
 if [ $? -ne 0 ]; then
     echo -e "${RED}Failed to copy .env to BASE_DIR. Exiting.${NC}"
     exit 1
